name: flutter_ladydenily
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # UI
  google_fonts: ^6.3.1
  flutx_core: ^1.1.0+1
  get: ^4.7.2
  pin_code_fields: ^8.0.1
  iconsax: ^0.0.8
  image_picker: ^1.2.0
  country_picker: ^2.0.27


#video_player:
  video_player: ^2.10.0


  # Network checker
  connectivity_plus: ^6.1.5

  # Api and cache
  dio: ^5.9.0
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  path_provider: ^2.1.5
  json_annotation: ^4.9.0
  crypto: ^3.0.6
  cached_network_image: ^3.4.1
  flutter_secure_storage: ^9.2.4
  webview_flutter: ^4.0.7

  # Formation
  intl: ^0.20.2
  equatable: ^2.0.7
  dartz: ^0.10.1
  file_picker: ^10.3.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/
     - assets/icons/
     - assets/video/
